name:                chigginspicks
version:             0.1.0.0
github:              "githubuser/chigginspicks"
license:             BSD3
author:              "rbas"
maintainer:          "ryanbas21@gmail.com"
copyright:           "2020 rbas"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/chigginspicks#readme>

dependencies:
- base >= 4.7 && < 5
- scotty
- aeson
- lens
- lens-aeson
- mtl
- containers
- text
- bytestring
- dotenv
- wreq

library:
  source-dirs: src
  main:                Main.hs
  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  dependencies:
  - chigginspicks

tests:
  chigginspicks-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chigginspicks
